name: ChunkClaim
version: '1.0-SNAPSHOT'
main: de.acGames.chunkClaim.ChunkClaim
api-version: '1.21'
commands:
  chunkclaim:
    op-required: true
    permission: "plugin.protection.op"
    permission-message: "You do not have permission to use this command."
